config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  resource :session
  resources :stories do
    collection do
      get "bin"
    end
    resources :votes
  end
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "stories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  after_create :create_initial_vote
  validates :name, :link, presence: true
  belongs_to :user
  has_many :votes do
    def latest
      order('id DESC').limit(4)
    end
  end

  scope :upcoming, -> { where("votes_count < 5").order("votes_count DESC")}
  scope :popular, -> { where("votes_count >= 5").order("id DESC")}

  def to_param
    # Overrides the to_param method defined by ActiveRecord::Base class. For URLs
    # Replaces non-text with dashes and returns remainder of text in lower case
    "#{id}-#{name.gsub(/\W/, '-').downcase}"
  end

  protected
    def create_initial_vote
      votes.create user: user
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :stories
  has_many :votes
  has_many :stories_voted_on,
    through: :votes,
    source: :story

  def to_param
    "#{id}-#{name}"
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :story, counter_cache: true
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user

  protected

  def current_user
    return unless session[:user_id]
    @current_user = User.where(id: session[:user_id]).first
  end

  def ensure_login
    return true if logged_in?
    session[:return_to] = request.fullpath
    redirect_to new_session_path and return false
  end

  def logged_in?
    !@current_user.nil?
  end
  helper_method :logged_in?
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @current_user = User.find_by(email: params[:email])
    if @current_user && @current_user.authenticate(params[:password])
      session[:user_id] = @current_user.id
      if session[:return_to]
        redirect_to session[:return_to]
        session[:return_to] = nil
      else
        redirect_to stories_path
      end
    else
      render action: 'new'
    end
  end

  def destroy
      session[:user_id] = @current_user = nil
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :ensure_login, only: [ :new, :create ]

  def index
    # @stories=fetch_stories('votes_count>=5')
    @stories = Story.popular
  end

  def bin
    # @stories=fetch_stories('votes_count<5')
    @stories = Story.upcoming
    render action: 'index'
  end

  def new
    @story=Story.new
  end

  def create
    @story = @current_user.stories.build story_params
    if @story.save
      flash[:notice]='Story submission succeeded'
      redirect_to stories_path
    else
      render action:'new'
    end
  end

  def show
    @story = Story.find(params[:id])
  end

  def story_params
    params.require(:story).permit(:name, :link, :description)
  end

  protected
  # def fetch_stories(conditions)
  #   @stories = Story.where(conditions).order("created_at DESC")
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @stories_submitted = @user.stories.limit(6).order("stories.id DESC")
    @stories_voted_on = @user.stories_voted_on.limit(6).order("votes.id DESC")
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :ensure_login
  def create
    @story = Story.find(params[:story_id])
    if @vote = @story.votes.create(user: @current_user)
      respond_to do |format|
        format.html { redirect_to @story, notice: 'Vote was successfully created.' }
        format.js {}
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
  def story_list_heading
    story_type = case controller.action_name
      when "index" then "front-page story"
      when "bin" then "upcoming story"
      end
    "Showing #{ pluralize(@stories.size, story_type) }"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Readit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="content">
      <div id="login_logout">
        <% if @current_user %>
          Logged in as:
          <%= @current_user.name %>
          <em><%= link_to "(Logout)", session_path, method: :delete %></em>
        <% else %>
          <em>Not logged in.</em>
          <%= link_to 'Login', new_session_path %>
        <% end %>
      </div>
      <h1>Readit</h1>
      <% unless flash[:notice].blank? %>
        <div id="notification"><%= flash[:notice] %></div>
      <% end %>
      <%= yield %>
    </div>

    <ul id="navigation">
      <li><%= link_to 'Front page stories', stories_path %></li>
      <li><%= link_to 'Upcoming stories', bin_stories_path %></li>
      <li><%= link_to 'Submit a new story!',new_story_path %></li>
    </ul>

  </body>
</html>

app/views/stories/_story.html.erb
<div class='story'>
  <h3><%= link_to story.name, story %></h3>
  <p>
    Submitted by: <%= story.user.name %> |
    Score: <%= story.votes_count %>
  </p>
</div>

app/views/stories/create.js.erb
$("#vote_score").html("Score: " + <%= @story.votes.size %>)
$("#vote_score").css({backgroundColor: "#ffffcc"});

setTimeout(function(){
  $("#vote_score").css({backgroundColor: "#ffffff"});
}, 2000);

$("#vote_history").html('<%= j(render partial: "votes/vote", collection: @story.votes.latest) %>')

app/views/stories/index.html.erb
<h2>
<%= story_list_heading %>
</h2>
<%= render partial: 'story', collection: @stories %>

app/views/stories/new.html.erb
<% if @story.errors.any? %>
  <div class="form_errors">
    <h3>Errors</h3>
    <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @story do |f| %>
  <div>
    <p><%= f.label :name %></p>
    <%= f.text_field :name %>
  </div>
  <div>
    <p><%= f.label :link %></p>
    <%= f.text_field :link %>
  </div>
  <div>
    <p><%= f.label :description %></p>
    <%= f.text_area :description %>
  </div>
  <div>
    <p><%= submit_tag %></p>
  </div>
<% end %>

app/views/stories/show.html.erb
<h2>
<span id="vote_score">
  Score: <%= @story.votes.size %>
</span>
<%= @story.name %>
</h2>

<ul id="vote_history">
  <% if @story.votes.empty? %>
    <em>No votes yet!</em>
  <% else %>
    <%= render partial:'votes/vote', collection: @story.votes.latest %>
  <% end %>
</ul>

<p>
  <%= @story.description %>
</p>

<p class="submitted_by">
  Submitted by:
  <span><%= link_to @story.user.name, @story.user %></span>
</p>

<p>
  <%= link_to @story.link, @story.link %>
</p>

<% if logged_in? %>
  <div id="vote_form">
    <%=form_for [@story, Vote.new], remote: true do |f| %>
      <%= f.submit 'Vote for it' %>
    <% end %>
    <!-- Alternative for above form_for code,being the 'Vote for it' button -->
    <!-- <%= form_tag story_votes_path(@story), remote: true do %>
      <%= submit_tag 'Vote for it' %>
    <% end %> -->
  </div>
<% else %>
  <p>
    <em>
      You would be able to vote for this story if you were
      <%= link_to 'logged in', new_session_path %>
    </em>
  </p>
<% end %>

app/views/users/show.html.erb
<h2>Stories submitted by <%= @user.name %></h2>
<div id="stories_submitted">
  <%= render partial: @stories_submitted %>
</div>
<h2>Stories voted for by <%= @user.name %></h2>
<div id="stories_voted_on">
  <%= render partial: @stories_voted_on %>
</div>

app/views/votes/_vote.html.erb
<li><%= vote.created_at.to_formatted_s(:short) %></li>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/votes/create.js.erb
$("#vote_score").html("Score: " + <%= @story.votes.size %>)
$("#vote_score").css({backgroundColor: "#ffffcc"});

$("#vote_history").html('<%= j( render partial: "votes/vote",
                                       collection: @story.votes.latest )  %>')
setTimeout(function(){
  $("#vote_score").css({backgroundColor: "#ffffff"});
}, 2000);